use std::collections::BTreeSet;
use std::collections::VecDeque;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;
use std::sync::Mutex;
use std::thread;
use std::time::Instant;

struct TritonKernelSpec {
    artifact_dir: &'static str,
    kernel_path: &'static str,
    kernel_name: &'static str,
    signature: &'static str,
    grid: &'static str,
    out_name: &'static str,
    num_warps: u32,
    num_stages: u32,
}

struct NvccTask {
    cu_file: PathBuf,
    obj_file: PathBuf,
    args: Vec<String>,
}

struct FlashInferIncludes {
    include: PathBuf,
    csrc: PathBuf,
    cutlass: PathBuf,
    cutlass_util: PathBuf,
    spdlog: PathBuf,
    /// Vendored CCCL (cub, libcudacxx, thrust). Must be passed as `-I` while the
    /// CTK include dir is `-isystem`, so these override the toolkit's older CCCL
    /// copy — FlashInfer v0.6+ uses APIs (e.g. `cuda::fast_mod_div`) that older
    /// CTK CCCL lacks. Mirrors upstream flashinfer/jit/cpp_ext.py ordering.
    cccl: Vec<PathBuf>,
}

const GLM52_TRTLLM_FMHA_CUBINS: &[(&str, &str)] = &[
    (
        "kGlm52FmhaSparseSeedQ8",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512PagedKvDenseStaticTokenSparseP1MultiCtasKvVarSeqQ8Kv128StaticSwapsAbForGen.cubin",
    ),
    (
        "kGlm52FmhaSparsePersistentSeedQ8",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512PagedKvDenseStaticTokenSparseP1VarSeqQ8Kv128PersistentSwapsAbForGen.cubin",
    ),
    (
        "kGlm52FmhaSparseShortQ8",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512HVPerCta128PagedKvDenseStaticTokenSparseP1VarSeqQ8Kv128PersistentSwapsAbForGen.cubin",
    ),
    (
        "kGlm52FmhaSparseLongQ8",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512HVPerCta128PagedKvDenseStaticTokenSparseP1MultiCtasKvVarSeqQ8Kv128StaticSwapsAbForGen.cubin",
    ),
    (
        "kGlm52FmhaSparseLongQ16",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512HVPerCta128PagedKvDenseStaticTokenSparseP1MultiCtasKvVarSeqQ16Kv128StaticSwapsAbForGen.cubin",
    ),
    (
        "kGlm52FmhaSparseLongQ16V256",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512HVPerCta256PagedKvDenseStaticTokenSparseP1MultiCtasKvVarSeqQ16Kv128StaticSwapsAbForGen.cubin",
    ),
    (
        "kGlm52FmhaSparseLongQ16V512",
        "fmhaSm100fKernel_QkvE4m3OBfloat16HQk576HV512PagedKvDenseStaticTokenSparseP1MultiCtasKvVarSeqQ16Kv128StaticSwapsAbForGen.cubin",
    ),
];

fn generate_glm52_trtllm_fmha_cubins(root: &Path, out_dir: &Path) {
    let cubin_dir = root.join("cubin/glm52");
    let mut generated = String::from(
        "// Generated by pegainfer-kernels/build.rs from the checked-in FlashInfer cubins.\n\
         #pragma once\n\n",
    );
    for &(symbol, file_name) in GLM52_TRTLLM_FMHA_CUBINS {
        let path = cubin_dir.join(file_name);
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = fs::read(&path).unwrap_or_else(|err| {
            panic!(
                "failed to read GLM5.2 TRTLLM FMHA cubin {}: {err}",
                path.display()
            )
        });
        writeln!(&mut generated, "static const unsigned char {symbol}[] = {{")
            .expect("write cubin array declaration");
        for chunk in bytes.chunks(16) {
            generated.push_str("  ");
            for byte in chunk {
                write!(&mut generated, "0x{byte:02x}, ").expect("write cubin byte");
            }
            generated.push('\n');
        }
        generated.push_str("};\n");
        writeln!(
            &mut generated,
            "static constexpr unsigned int {symbol}Size = sizeof({symbol});\n"
        )
        .expect("write cubin array size");
    }
    let output = out_dir.join("glm52_trtllm_fmha_cubins.inc");
    fs::write(&output, generated).unwrap_or_else(|err| {
        panic!(
            "failed to write generated GLM5.2 TRTLLM FMHA cubin header {}: {err}",
            output.display()
        )
    });
}

fn workspace_root() -> PathBuf {
    crate_root().join("..")
}

/// AOT-export the CuTe DSL tcgen05 fp8 GEMMs and compile the dispatch shim
/// around them (csrc/glm52/glm52_fp8_dsl_gemm.c). Opt-in via
/// `PEGAINFER_CUTEDSL_PYTHON` (a Python with torch + nvidia-cutlass-dsl on a
/// CUDA box); without it the shim compiles as an empty-table stub and the
/// runtime stays on the CUTLASS route. The exported objects resolve their
/// `_cuda*` wrapper symbols from the DSL wheel's libcute_dsl_runtime.so —
/// linked here, needed on LD_LIBRARY_PATH at run time.
fn build_glm52_cutedsl_fp8_dsl(root: &Path, out_dir: &Path, cuda_include: &Path) {
    println!("cargo:rerun-if-env-changed=PEGAINFER_CUTEDSL_PYTHON");
    let shim_c = root.join("csrc/glm52/glm52_fp8_dsl_gemm.c");
    println!("cargo:rerun-if-changed={}", shim_c.display());
    let mut shim = cc::Build::new();
    shim.include(cuda_include)
        .flag("-std=c11")
        .warnings(false)
        .file(&shim_c);
    if let Ok(python) = std::env::var("PEGAINFER_CUTEDSL_PYTHON") {
        let script = root.join("tools/cutedsl/export_glm52_fp8_dsl.py");
        let benches = workspace_root().join("pegainfer-glm52/benches");
        let gen_dir = out_dir.join("cutedsl_fp8_dsl");
        fs::create_dir_all(&gen_dir).expect("create the cutedsl gen dir");
        println!("cargo:rerun-if-changed={}", script.display());
        for source in [
            "kernel_lab/units/fp8_gemm_dsl_tc_kernel.py",
            "kernel_lab/units/fp8_gemm_dsl_tc.py",
        ] {
            println!("cargo:rerun-if-changed={}", benches.join(source).display());
        }
        let status = time_phase("cutedsl fp8 GEMM export", || {
            Command::new(&python)
                .arg(&script)
                .arg("--benches-dir")
                .arg(&benches)
                .arg("--out-dir")
                .arg(&gen_dir)
                .status()
        })
        .unwrap_or_else(|err| panic!("failed to run {python}: {err}"));
        assert!(
            status.success(),
            "CuTe DSL fp8 GEMM export failed (PEGAINFER_CUTEDSL_PYTHON={python})"
        );
        let mut objects: Vec<PathBuf> = fs::read_dir(&gen_dir)
            .expect("read the cutedsl gen dir")
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                (path.extension().and_then(|e| e.to_str()) == Some("o")).then_some(path)
            })
            .collect();
        objects.sort();
        assert!(!objects.is_empty(), "cutedsl export produced no objects");
        let object_count = objects.len();
        for object in objects {
            shim.object(object);
        }
        shim.define("GLM52_CUTEDSL_AOT", None).include(&gen_dir);
        let lib_dir_probe = Command::new(&python)
            .args([
                "-c",
                "import cutlass, os; print(os.path.abspath(os.path.join(os.path.dirname(cutlass.__file__), '..', '..', 'lib')))",
            ])
            .output()
            .expect("probe the nvidia-cutlass-dsl lib dir");
        let lib_dir = String::from_utf8_lossy(&lib_dir_probe.stdout)
            .trim()
            .to_string();
        assert!(
            Path::new(&lib_dir).join("libcute_dsl_runtime.so").exists(),
            "libcute_dsl_runtime.so not found under {lib_dir}"
        );
        println!("cargo:rustc-link-search=native={lib_dir}");
        println!("cargo:rustc-link-lib=dylib=cute_dsl_runtime");
        println!(
            "cargo:warning=GLM5.2 CuTe DSL fp8 GEMM AOT enabled: {object_count} objects; \
             libcute_dsl_runtime.so ({lib_dir}) must be on LD_LIBRARY_PATH at run time"
        );
    }
    time_phase("cc glm52_fp8_dsl_gemm", || {
        shim.compile("glm52_fp8_dsl_gemm");
    });
}

fn crate_root() -> PathBuf {
    PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"))
}

fn ensure_git_submodules_initialized(repo_root: &Path) {
    if !repo_root.join(".git").exists() || !repo_root.join(".gitmodules").is_file() {
        return;
    }

    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join(".gitmodules").display()
    );

    let output = Command::new("git")
        .args(["submodule", "status", "--recursive"])
        .current_dir(repo_root)
        .output()
        .unwrap_or_else(|err| {
            panic!(
                "Failed to inspect git submodules from {}: {err}. \
                 Install git or run `git submodule update --init --recursive` manually.",
                repo_root.display()
            )
        });
    assert!(
        output.status.success(),
        "Failed to inspect git submodules from {}. stdout: {} stderr: {}",
        repo_root.display(),
        String::from_utf8_lossy(&output.stdout).trim(),
        String::from_utf8_lossy(&output.stderr).trim()
    );

    if !String::from_utf8_lossy(&output.stdout)
        .lines()
        .any(|line| line.starts_with('-'))
    {
        return;
    }

    println!("cargo:warning=Initializing missing git submodules for first build");
    let output = Command::new("git")
        .args(["submodule", "update", "--init", "--recursive"])
        .current_dir(repo_root)
        .output()
        .unwrap_or_else(|err| {
            panic!(
                "Failed to initialize git submodules from {}: {err}. \
                 Run `git submodule update --init --recursive` manually.",
                repo_root.display()
            )
        });
    assert!(
        output.status.success(),
        "Failed to initialize git submodules from {}. stdout: {} stderr: {}",
        repo_root.display(),
        String::from_utf8_lossy(&output.stdout).trim(),
        String::from_utf8_lossy(&output.stderr).trim()
    );
}

fn build_timing_enabled() -> bool {
    std::env::var("PEGAINFER_BUILD_TIMING").is_ok_and(|value| {
        let value = value.trim().to_ascii_lowercase();
        !(value.is_empty() || value == "0" || value == "false" || value == "off")
    })
}

fn time_phase<T>(label: impl AsRef<str>, f: impl FnOnce() -> T) -> T {
    if !build_timing_enabled() {
        return f();
    }

    let started = Instant::now();
    let result = f();
    println!(
        "cargo:warning=build-timing {} {:.3}s",
        label.as_ref(),
        started.elapsed().as_secs_f64()
    );
    result
}

fn parse_job_count_env(name: &str) -> Option<usize> {
    let value = std::env::var(name).ok()?;
    match value.trim().parse::<usize>() {
        Ok(jobs) if jobs > 0 => Some(jobs),
        _ => {
            println!("cargo:warning=Ignoring invalid {name}={value}; expected a positive integer.");
            None
        }
    }
}

fn nvcc_job_count() -> usize {
    if let Some(jobs) = parse_job_count_env("PEGAINFER_NVCC_JOBS") {
        return jobs;
    }

    parse_job_count_env("NUM_JOBS")
        .or_else(|| thread::available_parallelism().ok().map(usize::from))
        .unwrap_or(1)
        .max(1)
}

fn nvcc_task_priority(cu_file: &Path) -> usize {
    match cu_file.file_stem().and_then(|stem| stem.to_str()) {
        Some("paged_attention") => 0,
        Some("paged_attention_hd512" | "flashinfer_sampling") => 1,
        Some("flashinfer_top1") => 2,
        Some("flashinfer_norm") => 3,
        _ => 10,
    }
}

fn parse_sm_token(raw: &str) -> Option<String> {
    let token = raw.trim().trim_matches('"');
    if token.is_empty() {
        return None;
    }

    let token = token
        .strip_prefix("sm_")
        .or_else(|| token.strip_prefix("compute_"))
        .unwrap_or(token);

    if let Some((major, minor)) = token.split_once('.') {
        let digit_count = minor.chars().take_while(char::is_ascii_digit).count();
        let (minor_digits, suffix) = minor.split_at(digit_count);
        if major.chars().all(|c| c.is_ascii_digit())
            && !minor_digits.is_empty()
            && suffix.chars().all(|c| c.is_ascii_alphabetic())
        {
            return Some(format!("{major}{minor_digits}{suffix}"));
        }
        return None;
    }

    let digit_count = token.chars().take_while(char::is_ascii_digit).count();
    let (digits, suffix) = token.split_at(digit_count);
    if !digits.is_empty() && suffix.chars().all(|c| c.is_ascii_alphabetic()) {
        if digits.len() == 1 {
            return Some(format!("{digits}0{suffix}"));
        }
        return Some(format!("{digits}{suffix}"));
    }

    None
}

fn nvcc_supported_arches(nvcc: &str) -> Option<BTreeSet<String>> {
    let output = Command::new(nvcc).arg("--list-gpu-arch").output().ok()?;
    if !output.status.success() {
        return None;
    }

    Some(
        String::from_utf8_lossy(&output.stdout)
            .lines()
            .map(str::trim)
            .filter(|line| line.starts_with("compute_"))
            .map(str::to_string)
            .collect(),
    )
}

fn normalize_nvcc_sm(sm: &str, supported_arches: Option<&BTreeSet<String>>) -> String {
    let preferred = match sm {
        "120" | "120f" => Some("120f"),
        "121" | "121a" => Some("121a"),
        _ => None,
    };
    if let Some(preferred) = preferred {
        if supported_arches.is_some_and(|arches| arches.contains(&format!("compute_{preferred}"))) {
            return preferred.to_string();
        }
        let raw = sm_numeric_prefix(sm).map_or_else(|| sm.to_string(), |sm| sm.to_string());
        println!(
            "cargo:warning=nvcc does not list compute_{preferred}; compiling CUDA kernels for raw sm_{raw}"
        );
        return raw;
    }
    sm.to_string()
}

fn normalize_nvcc_sms(sm_targets: &[String], nvcc: &str) -> Vec<String> {
    let supported_arches = nvcc_supported_arches(nvcc);
    sm_targets
        .iter()
        .map(|sm| normalize_nvcc_sm(sm, supported_arches.as_ref()))
        .collect()
}

fn sm_targets_from_nvidia_smi() -> Option<Vec<String>> {
    let output = Command::new("nvidia-smi")
        .args(["--query-gpu=compute_cap", "--format=csv,noheader"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut sms = BTreeSet::new();
    for line in stdout.lines() {
        let cap = line.split(',').next().unwrap_or(line).trim();
        if let Some(sm) = parse_sm_token(cap) {
            sms.insert(sm);
        }
    }

    if sms.is_empty() {
        None
    } else {
        Some(sms.into_iter().collect())
    }
}

fn detect_sm_targets() -> Vec<String> {
    if let Ok(env) = std::env::var("PEGAINFER_CUDA_SM").or_else(|_| std::env::var("CUDA_SM")) {
        let mut sms = Vec::new();
        for token in env.split(',') {
            if let Some(sm) = parse_sm_token(token) {
                sms.push(sm);
            } else {
                print!(
                    "cargo:warning=Invalid SM token '{}' in CUDA_SM environment variable, skipping.",
                    token
                );
            }
        }
        if !sms.is_empty() {
            return sms;
        }
        print!(
            "cargo:warning=No valid SM tokens found in CUDA_SM environment variable '{}', falling back to auto-detection.",
            env
        );
    }

    if let Some(sms) = sm_targets_from_nvidia_smi() {
        return sms;
    }

    print!(
        "cargo:warning=Failed to detect GPU SMs via nvidia-smi. Set PEGAINFER_CUDA_SM/CUDA_SM environment variable to override."
    );
    panic!("GPU detection failed");
}

fn nvcc_arch_args(normalized_sms: &[String]) -> Vec<String> {
    let mut args = Vec::new();
    for sm in normalized_sms {
        args.push("-gencode".to_string());
        args.push(format!("arch=compute_{sm},code=sm_{sm}"));
    }

    if let Some(max_sm) = normalized_sms
        .iter()
        .max_by_key(|sm| sm_numeric_prefix(sm).unwrap_or(0))
    {
        args.push("-gencode".to_string());
        args.push(format!("arch=compute_{max_sm},code=compute_{max_sm}"));
    }

    args
}

fn nvcc_accepts_gencode(nvcc: &str, compute: &str, sm: &str) -> bool {
    let stem = format!(
        "pegainfer_nvcc_probe_{}_compute_{compute}_sm_{sm}",
        std::process::id()
    );
    let cu_path = std::env::temp_dir().join(format!("{stem}.cu"));
    let obj_path = std::env::temp_dir().join(format!("{stem}.o"));
    if let Err(err) = fs::write(
        &cu_path,
        "extern \"C\" __global__ void pegainfer_nvcc_probe() {}\n",
    ) {
        println!(
            "cargo:warning=Failed to write nvcc probe {}: {err}",
            cu_path.display()
        );
        return false;
    }

    let output = Command::new(nvcc)
        .args(["-c"])
        .arg(&cu_path)
        .arg("-o")
        .arg(&obj_path)
        .arg("-gencode")
        .arg(format!("arch=compute_{compute},code=sm_{sm}"))
        .output();
    let _ = fs::remove_file(&cu_path);
    let _ = fs::remove_file(&obj_path);

    match output {
        Ok(output) if output.status.success() => true,
        Ok(output) => {
            println!(
                "cargo:warning=nvcc rejected compute_{compute}/sm_{sm} probe: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            );
            false
        }
        Err(err) => {
            println!("cargo:warning=Failed to run nvcc arch probe: {err}");
            false
        }
    }
}

fn glm52_fp8_gemm_arch_args(normalized_sms: &[String], nvcc: &str) -> Option<Vec<String>> {
    let mut args = Vec::new();
    for sm in normalized_sms {
        let numeric = sm_numeric_prefix(sm)?;
        if !(100..120).contains(&numeric) {
            continue;
        }
        let accelerated = format!("{numeric}a");
        if !nvcc_accepts_gencode(nvcc, &accelerated, &accelerated) {
            continue;
        }
        args.push("-gencode".to_string());
        args.push(format!("arch=compute_{accelerated},code=sm_{accelerated}"));
    }
    (!args.is_empty()).then_some(args)
}

fn glm52_flashmla_sparse_arch_args(normalized_sms: &[String], nvcc: &str) -> Vec<String> {
    let sm90a_supported = normalized_sms.iter().any(|sm| sm == "90" || sm == "90a")
        && nvcc_accepts_gencode(nvcc, "90a", "90a");
    let sm100f_supported = normalized_sms
        .iter()
        .any(|sm| sm_numeric_prefix(sm).is_some_and(|n| (100..120).contains(&n)))
        && nvcc_accepts_gencode(nvcc, "100f", "100f");

    let mut targets = Vec::new();
    for sm in normalized_sms {
        let target = match sm_numeric_prefix(sm) {
            Some(90) => {
                if sm90a_supported {
                    Some(("90a", "90a", "sm_90a"))
                } else {
                    println!(
                        "cargo:warning=nvcc cannot compile compute_90a/sm_90a; GLM5.2 FlashMLA sparse decode will use sm_{sm}"
                    );
                    Some((sm.as_str(), sm.as_str(), "native"))
                }
            }
            Some(100..=119) => {
                if sm100f_supported {
                    Some(("100f", "100f", "sm_100f"))
                } else {
                    println!(
                        "cargo:warning=nvcc cannot compile compute_100f/sm_100f; GLM5.2 FlashMLA sparse decode will use sm_{sm}"
                    );
                    Some((sm.as_str(), sm.as_str(), "native"))
                }
            }
            _ => Some((sm.as_str(), sm.as_str(), "native")),
        };
        if let Some(target) = target {
            if !targets.iter().any(|existing| existing == &target) {
                targets.push(target);
            }
        }
    }

    let labels = targets
        .iter()
        .map(|(_, sm, label)| {
            if *label == "native" {
                format!("sm_{sm}")
            } else {
                label.to_string()
            }
        })
        .collect::<Vec<_>>();
    if labels
        != normalized_sms
            .iter()
            .map(|sm| format!("sm_{sm}"))
            .collect::<Vec<_>>()
    {
        println!(
            "cargo:warning=Compiling GLM5.2 FlashMLA sparse decode for nvcc targets: {}",
            labels.join(",")
        );
    }

    let mut args = Vec::new();
    for (compute, sm, _) in targets {
        args.push("-gencode".to_string());
        args.push(format!("arch=compute_{compute},code=sm_{sm}"));
    }
    args
}

/// Arch args for the AOT-instantiated DeepGEMM MQA kernels. GLM5.2 is
/// Blackwell-only: assembled as sm_100f (tcgen05). Hopper SM90A path removed.
fn glm52_deepgemm_mqa_arch_args(
    normalized_sms: &[String],
    nvcc: &str,
) -> Option<(Vec<String>, String)> {
    let has_sm100 = normalized_sms
        .iter()
        .any(|sm| sm_numeric_prefix(sm).is_some_and(|n| (100..120).contains(&n)));
    if has_sm100 && nvcc_accepts_gencode(nvcc, "100f", "100f") {
        return Some((
            vec![
                "-gencode".to_string(),
                "arch=compute_100f,code=sm_100f".to_string(),
            ],
            "-DGLM52_DEEPGEMM_MQA_SM100F".to_string(),
        ));
    }

    None
}

/// Arch args for TUs whose device code is raw Blackwell tcgen05: sm_100f
/// ONLY (family arch — runs on the whole sm_10x line, incl. GB300's sm_103).
/// Returns `None` when no sm_100 target is present (or nvcc lacks 100f); the
/// TU then compiles its NOT_SUPPORTED stub for the requested targets instead.
fn glm52_sm100f_only_arch_args(normalized_sms: &[String], nvcc: &str) -> Option<Vec<String>> {
    let has_sm100 = normalized_sms
        .iter()
        .any(|sm| sm_numeric_prefix(sm).is_some_and(|n| (100..120).contains(&n)));
    (has_sm100 && nvcc_accepts_gencode(nvcc, "100f", "100f")).then(|| {
        vec![
            "-gencode".to_string(),
            "arch=compute_100f,code=sm_100f".to_string(),
        ]
    })
}

fn collect_files_recursively(dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("Failed to read {}: {err}", dir.display()))
        .map(|entry| {
            entry.unwrap_or_else(|err| panic!("Failed to read entry in {}: {err}", dir.display()))
        })
        .collect();
    entries.sort_by_key(std::fs::DirEntry::path);

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_files_recursively(&path, out);
        } else {
            out.push(path);
        }
    }
}

fn is_deepseek_v2_lite_source(csrc_dir: &Path, path: &Path) -> bool {
    match path.strip_prefix(csrc_dir) {
        Ok(relative) => relative
            .components()
            .any(|part| part.as_os_str() == "deepseek_v2_lite"),
        Err(_) => false,
    }
}

fn is_kimi_k2_source(csrc_dir: &Path, path: &Path) -> bool {
    match path.strip_prefix(csrc_dir) {
        Ok(relative) => relative
            .components()
            .any(|part| part.as_os_str() == "kimi_k2"),
        Err(_) => false,
    }
}

/// DeepEP elastic shim (csrc/deepep/): shared MoE EP all-to-all substrate.
/// Compiled only with the `moe` feature; needs NCCL >= 2.30.4 headers/lib.
fn is_deepep_source(csrc_dir: &Path, path: &Path) -> bool {
    match path.strip_prefix(csrc_dir) {
        Ok(relative) => relative
            .components()
            .any(|part| part.as_os_str() == "deepep"),
        Err(_) => false,
    }
}

/// GLM5.2 model-local CUDA shims over DeepGEMM/FlashMLA contracts.
fn is_glm52_source(csrc_dir: &Path, path: &Path) -> bool {
    match path.strip_prefix(csrc_dir) {
        Ok(relative) => relative
            .components()
            .any(|part| part.as_os_str() == "glm52"),
        Err(_) => false,
    }
}

fn is_higgs_audio_source(csrc_dir: &Path, path: &Path) -> bool {
    match path.strip_prefix(csrc_dir) {
        Ok(relative) => relative
            .components()
            .any(|part| part.as_os_str() == "higgs_audio"),
        Err(_) => false,
    }
}

fn require_submodule_file(root: &Path, feature: &str, label: &str, relative: &str) {
    let path = root.join(relative);
    assert!(
        path.exists(),
        "The {feature} feature requires the {label} submodule. Missing {}. Run `git submodule update --init --recursive {}`.",
        path.display(),
        relative
    );
}

fn require_moe_submodules(root: &Path) {
    require_submodule_file(root, "moe", "DeepEP", "third_party/DeepEP/README.md");
    require_submodule_file(root, "moe", "DeepGEMM", "third_party/DeepGEMM/README.md");
    require_submodule_file(
        root,
        "moe",
        "FlashMLA",
        "third_party/FlashMLA/csrc/params.h",
    );
}

fn require_glm52_submodules(root: &Path) {
    require_submodule_file(
        root,
        "glm52",
        "FlashMLA nested CUTLASS",
        "third_party/FlashMLA/csrc/cutlass/include/cutlass/bfloat16.h",
    );
}

/// NCCL >= 2.30.4 root (include/nccl.h + lib/libnccl.so.2) for the DeepEP
/// shim's device API (ncclDevComm / windows / GIN). cudarc dlopens whatever
/// libnccl.so.2 it finds at runtime, so build and runtime must point at the
/// same install: set PEGAINFER_NCCL_ROOT and put `$PEGAINFER_NCCL_ROOT/lib`
/// on LD_LIBRARY_PATH. The nvidia-nccl-cu13 wheel layout works directly:
///   pip download 'nvidia-nccl-cu13>=2.30.4' --no-deps -d /tmp/nccl \
///     && unzip /tmp/nccl/*.whl 'nvidia/nccl/*' -d /tmp/nccl \
///     && export PEGAINFER_NCCL_ROOT=/tmp/nccl/nvidia/nccl
fn deepep_nccl_root() -> PathBuf {
    let Ok(root) = std::env::var("PEGAINFER_NCCL_ROOT").map(PathBuf::from) else {
        panic!(
            "The moe feature builds the DeepEP shim, which needs NCCL >= 2.30.4. \
             Set PEGAINFER_NCCL_ROOT to an install with include/nccl.h and lib/libnccl.so.2 \
             (e.g. the unpacked nvidia-nccl-cu13 wheel)."
        )
    };

    let header = root.join("include/nccl.h");
    let contents = fs::read_to_string(&header).unwrap_or_else(|err| {
        panic!(
            "PEGAINFER_NCCL_ROOT: cannot read {}: {err}",
            header.display()
        )
    });
    let version_component = |name: &str| -> u32 {
        contents
            .lines()
            .find_map(|line| line.strip_prefix(&format!("#define {name} ")))
            .and_then(|value| value.trim().parse().ok())
            .unwrap_or_else(|| panic!("{} does not define {name}", header.display()))
    };
    let version = version_component("NCCL_MAJOR") * 10000
        + version_component("NCCL_MINOR") * 100
        + version_component("NCCL_PATCH");
    assert!(
        version >= 23004,
        "PEGAINFER_NCCL_ROOT points at NCCL {version} (< 2.30.4); the DeepEP shim needs the \
         NCCL device API"
    );

    let lib = root.join("lib/libnccl.so.2");
    assert!(
        lib.is_file(),
        "PEGAINFER_NCCL_ROOT: {} not found",
        lib.display()
    );
    root
}

/// The wheel ships only libnccl.so.2; give the linker the unversioned name it
/// wants via a symlink in OUT_DIR (already on the link search path). The
/// resulting DT_NEEDED is the soname (libnccl.so.2), resolved at runtime from
/// LD_LIBRARY_PATH.
fn link_deepep_nccl(nccl_root: &Path, out_dir: &Path) {
    let link_name = out_dir.join("libnccl.so");
    let target = nccl_root.join("lib/libnccl.so.2");
    match fs::read_link(&link_name) {
        Ok(existing) if existing == target => {}
        _ => {
            let _ = fs::remove_file(&link_name);
            std::os::unix::fs::symlink(&target, &link_name)
                .unwrap_or_else(|err| panic!("Failed to symlink {}: {err}", link_name.display()));
        }
    }
    println!("cargo:rustc-link-lib=dylib=nccl");
}

/// Link the freshly compiled CUDA objects into `libglm52_kernel_lab.so` for
/// the kernel-lab Python harness (`PEGAINFER_KERNEL_LAB=1` only). The objects
/// are already PIC (every nvcc task adds `--compiler-options -fPIC`), so the
/// same .o files that feed `libkernels_cuda.a` link into a shared object
/// without a second compile pass. DeepEP shim objects reference NCCL symbols
/// that stay unresolved in the .so — the harness dlopens with `RTLD_LAZY` and
/// never calls into DeepEP for these units.
fn link_kernel_lab_shared(
    nvcc: &str,
    toolkit: &pegainfer_build::CudaToolkit,
    out_dir: &Path,
    obj_files: &[PathBuf],
) {
    let so_path = out_dir.join("libglm52_kernel_lab.so");
    let _ = fs::remove_file(&so_path);
    let mut args = vec!["-shared".to_string()];
    args.extend(
        obj_files
            .iter()
            .map(|path| path.to_string_lossy().to_string()),
    );
    args.extend([
        "-o".to_string(),
        so_path.to_string_lossy().to_string(),
        format!("-L{}", toolkit.root.join("lib64").display()),
        "-lcudart".to_string(),
        "-lcublas".to_string(),
        "-lcublasLt".to_string(),
        "-lnvrtc".to_string(),
        "-lcuda".to_string(),
        "-lstdc++".to_string(),
    ]);
    let status = time_phase("nvcc -shared libglm52_kernel_lab.so", || {
        Command::new(nvcc)
            .args(&args)
            .status()
            .expect("Failed to run nvcc for libglm52_kernel_lab.so")
    });
    assert!(status.success(), "kernel-lab shared link failed");

    // Stable discovery path: OUT_DIR is target/<profile>/build/<pkg>-<hash>/out,
    // so three parents up is target/<profile>.
    if let Some(profile_dir) = out_dir
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
    {
        let stable = profile_dir.join("libglm52_kernel_lab.so");
        fs::copy(&so_path, &stable).unwrap_or_else(|err| {
            panic!(
                "Failed to copy kernel-lab .so to {}: {err}",
                stable.display()
            )
        });
        println!("cargo:warning=kernel_lab .so: {}", stable.display());
    } else {
        println!(
            "cargo:warning=kernel_lab .so: {} (no stable target/<profile> copy)",
            so_path.display()
        );
    }
}

fn cuda_object_name(csrc_dir: &Path, cu_file: &Path) -> String {
    let Some(relative) = cu_file.strip_prefix(csrc_dir).ok() else {
        return format!("{}_cuda.o", cu_file.file_stem().unwrap().to_string_lossy());
    };

    let mut parts: Vec<String> = relative
        .components()
        .filter_map(|component| component.as_os_str().to_str().map(ToOwned::to_owned))
        .collect();
    if let Some(last) = parts.last_mut() {
        if let Some(stem) = Path::new(last).file_stem().and_then(|stem| stem.to_str()) {
            *last = stem.to_string();
        }
    }

    format!("{}_cuda.o", parts.join("_"))
}

fn probe_triton_python(candidate: &str) -> Result<String, String> {
    let output = Command::new(candidate)
        .args(["-c", "import triton"])
        .output()
        .map_err(|err| format!("{candidate}: {err}"))?;

    if output.status.success() {
        Ok(candidate.to_string())
    } else {
        Err(format!(
            "{candidate}: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ))
    }
}

fn find_triton_python() -> Result<String, String> {
    if let Ok(candidate) = std::env::var("PEGAINFER_TRITON_PYTHON") {
        let candidate = candidate.trim();
        if candidate.is_empty() {
            return Err(
                "PEGAINFER_TRITON_PYTHON is set but empty. See pegainfer-kernels/tools/triton/README.md.".to_string(),
            );
        }
        return probe_triton_python(candidate).map_err(|message| {
            format!(
                "PEGAINFER_TRITON_PYTHON=`{candidate}` could not import Triton. {message}. See pegainfer-kernels/tools/triton/README.md."
            )
        });
    }

    let local_venv = workspace_root().join(".venv/bin/python");
    let mut diagnostics = Vec::new();
    let mut candidates = Vec::new();
    if local_venv.exists() {
        candidates.push(local_venv.to_string_lossy().to_string());
    }
    candidates.extend(["python3".to_string(), "python".to_string()]);

    for candidate in candidates {
        match probe_triton_python(&candidate) {
            Ok(path) => return Ok(path),
            Err(message) => diagnostics.push(message),
        }
    }

    Err(format!(
        "Could not find a Python interpreter with Triton installed. Set PEGAINFER_TRITON_PYTHON, bootstrap .venv, or ensure `python3 -c 'import triton'` works. Probe results: {}.",
        diagnostics.join(" | ")
    ))
}

fn first_existing_dir(candidates: &[PathBuf], fallback: PathBuf) -> PathBuf {
    candidates
        .iter()
        .find(|path| path.exists())
        .cloned()
        .unwrap_or(fallback)
}

fn flashinfer_includes() -> FlashInferIncludes {
    let crate_root = crate_root();
    let root = workspace_root();

    if let Ok(path) = std::env::var("PEGAINFER_FLASHINFER_INCLUDE") {
        let path = PathBuf::from(path);
        if path.join("flashinfer/sampling.cuh").exists() {
            return flashinfer_includes_from_include(path);
        }
        println!(
            "cargo:warning=PEGAINFER_FLASHINFER_INCLUDE={} does not contain flashinfer/sampling.cuh; falling back.",
            path.display()
        );
    }

    let candidates = [
        crate_root.join("third_party/flashinfer/include"),
        root.join("third_party/flashinfer/include"),
        root.join(".venv/lib/python3.13/site-packages/flashinfer/data/include"),
        root.join(".venv/lib/python3.12/site-packages/flashinfer/data/include"),
        root.join(".venv/lib/python3.11/site-packages/flashinfer/data/include"),
        root.join(".venv/lib/python3.10/site-packages/flashinfer/data/include"),
        root.join("../.venv/lib/python3.13/site-packages/flashinfer/data/include"),
        root.join("../.venv/lib/python3.12/site-packages/flashinfer/data/include"),
        root.join("../.venv/lib/python3.11/site-packages/flashinfer/data/include"),
        root.join("../.venv/lib/python3.10/site-packages/flashinfer/data/include"),
    ];

    for candidate in candidates {
        if candidate.join("flashinfer/sampling.cuh").exists() {
            return flashinfer_includes_from_include(candidate);
        }
    }

    flashinfer_includes_from_include(crate_root.join("third_party/flashinfer/include"))
}

fn flashinfer_includes_from_include(include: PathBuf) -> FlashInferIncludes {
    let flashinfer_root = include
        .parent()
        .expect("FlashInfer include dir must have a parent")
        .to_path_buf();

    let csrc = flashinfer_root.join("csrc");
    let cutlass = first_existing_dir(
        &[
            flashinfer_root.join("3rdparty/cutlass/include"),
            flashinfer_root.join("cutlass/include"),
        ],
        flashinfer_root.join("cutlass/include"),
    );
    let cutlass_util = first_existing_dir(
        &[
            flashinfer_root.join("3rdparty/cutlass/tools/util/include"),
            flashinfer_root.join("cutlass/tools/util/include"),
        ],
        flashinfer_root.join("cutlass/tools/util/include"),
    );
    let spdlog = first_existing_dir(
        &[
            flashinfer_root.join("3rdparty/spdlog/include"),
            flashinfer_root.join("spdlog/include"),
        ],
        flashinfer_root.join("spdlog/include"),
    );
    let cccl_root = first_existing_dir(
        &[
            flashinfer_root.join("3rdparty/cccl"),
            flashinfer_root.join("cccl"),
        ],
        flashinfer_root.join("3rdparty/cccl"),
    );
    let cccl = vec![
        cccl_root.join("cub"),
        cccl_root.join("libcudacxx/include"),
        cccl_root.join("thrust"),
    ];

    FlashInferIncludes {
        include,
        csrc,
        cutlass,
        cutlass_util,
        spdlog,
        cccl,
    }
}

fn triton_target(sm_targets: &[String]) -> String {
    let max_sm = sm_targets
        .iter()
        .filter_map(|sm| sm_numeric_prefix(sm))
        .max()
        .expect("expected at least one CUDA SM target for Triton AOT");

    if sm_targets.len() > 1 {
        println!(
            "cargo:warning=Triton AOT currently emits one cubin per kernel spec; using highest detected target sm_{max_sm}. Set PEGAINFER_CUDA_SM to pin one target explicitly."
        );
    }

    format!("cuda:{max_sm}:32")
}

fn sm_numeric_prefix(sm: &str) -> Option<u32> {
    let digits = sm
        .chars()
        .take_while(char::is_ascii_digit)
        .collect::<String>();
    if digits.is_empty() {
        None
    } else {
        digits.parse::<u32>().ok()
    }
}

fn generate_triton_artifacts(
    python: &str,
    out_dir: &Path,
    triton_target: &str,
    spec: &TritonKernelSpec,
) -> (String, PathBuf) {
    let root = crate_root();
    let generator_path = root.join("tools/triton/gen_triton_aot.py");
    let artifact_dir = out_dir.join("triton_aot").join(spec.artifact_dir);

    let output = time_phase(format!("triton-gen {}", spec.kernel_name), || {
        Command::new(python)
            .arg(&generator_path)
            .arg("--kernel-path")
            .arg(root.join(spec.kernel_path))
            .arg("--kernel-name")
            .arg(spec.kernel_name)
            .arg("--signature")
            .arg(spec.signature)
            .arg("--grid")
            .arg(spec.grid)
            .arg("--out-name")
            .arg(spec.out_name)
            .arg("--out-dir")
            .arg(&artifact_dir)
            .arg("--target")
            .arg(triton_target)
            .arg("--num-warps")
            .arg(spec.num_warps.to_string())
            .arg("--num-stages")
            .arg(spec.num_stages.to_string())
            .output()
            .unwrap_or_else(|err| {
                panic!(
                    "failed to run Triton AOT generator for {}: {err}",
                    spec.kernel_name
                )
            })
    });

    assert!(
        output.status.success(),
        "Triton AOT generator failed for {}. stdout: {} stderr: {}",
        spec.kernel_name,
        String::from_utf8_lossy(&output.stdout).trim(),
        String::from_utf8_lossy(&output.stderr).trim(),
    );

    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut func_name = None;
    let mut c_path = None;
    for line in stdout.lines() {
        if let Some(value) = line.strip_prefix("FUNC_NAME=") {
            func_name = Some(value.trim().to_string());
        } else if let Some(value) = line.strip_prefix("C_PATH=") {
            c_path = Some(PathBuf::from(value.trim()));
        }
    }

    let func_name = func_name.expect("Triton generator did not print FUNC_NAME");
    let c_path = c_path.expect("Triton generator did not print C_PATH");
    patch_triton_aot_per_device_handles(&c_path);
    (func_name, c_path)
}

fn patch_triton_aot_per_device_handles(c_path: &Path) {
    let src = fs::read_to_string(c_path).expect("failed to read generated Triton C source");
    let module_name = src
        .lines()
        .find_map(|line| line.strip_prefix("CUmodule "))
        .and_then(|rest| rest.strip_suffix(" = NULL;"))
        .map(str::to_string)
        .expect("generated Triton C source should declare one CUmodule");
    let function_name = src
        .lines()
        .find_map(|line| line.strip_prefix("CUfunction "))
        .and_then(|rest| rest.strip_suffix(" = NULL;"))
        .map(str::to_string)
        .expect("generated Triton C source should declare one CUfunction");

    let device_table_define = "#define PEGAINFER_TRITON_DEVICE_TABLE_SIZE 16\n\n";
    let device_helper = "\n\nstatic CUresult pegainfer_triton_current_device(CUdevice *dev) {\n  CUresult err = cuCtxGetDevice(dev);\n  if (err != CUDA_SUCCESS) {\n    return err;\n  }\n  if (*dev < 0 || *dev >= PEGAINFER_TRITON_DEVICE_TABLE_SIZE) {\n    return CUDA_ERROR_INVALID_DEVICE;\n  }\n  return CUDA_SUCCESS;\n}";

    let patched = src
        .replace(
            &format!("CUmodule {module_name} = NULL;"),
            &format!(
                "{device_table_define}CUmodule {module_name}[PEGAINFER_TRITON_DEVICE_TABLE_SIZE] = {{0}};"
            ),
        )
        .replace(
            &format!("CUfunction {function_name} = NULL;"),
            &format!(
                "CUfunction {function_name}[PEGAINFER_TRITON_DEVICE_TABLE_SIZE] = {{0}};{device_helper}"
            ),
        )
        .replace(
            &format!("CUDA_CHECK(cuModuleUnload({module_name}));"),
            &format!(
                "CUdevice dev = 0;\n    CUDA_CHECK(pegainfer_triton_current_device(&dev));\n    if ({module_name}[dev] != NULL) {{\n      CUDA_CHECK(cuModuleUnload({module_name}[dev]));\n      {module_name}[dev] = NULL;\n      {function_name}[dev] = NULL;\n    }}"
            ),
        );
    let patched = patched
        .replace(
            &format!("cuModuleLoadData(&{module_name}, bin)"),
            &format!("cuModuleLoadData(&{module_name}[dev], bin)"),
        )
        .replace(
            &format!("cuModuleGetFunction(&{function_name}, {module_name}, "),
            &format!("cuModuleGetFunction(&{function_name}[dev], {module_name}[dev], "),
        )
        .replace(
            &format!("cuFuncSetCacheConfig({function_name}, "),
            &format!("cuFuncSetCacheConfig({function_name}[dev], "),
        )
        .replace(
            &format!("cuFuncSetAttribute({function_name}, "),
            &format!("cuFuncSetAttribute({function_name}[dev], "),
        )
        .replace(
            &format!("if ({function_name} == NULL)\n       load_"),
            &format!("CUdevice dev = 0;\n    CUDA_CHECK(pegainfer_triton_current_device(&dev));\n    if ({function_name}[dev] == NULL)\n       load_"),
        )
        .replace(
            &format!("return cuLaunchKernel({function_name}, "),
            &format!("return cuLaunchKernel({function_name}[dev], "),
        )
        .replace(
            "int dev = 0;\n    void *bin =",
            "CUdevice dev = 0;\n    CUDA_CHECK(pegainfer_triton_current_device(&dev));\n    void *bin =",
        );

    fs::write(c_path, patched).expect("failed to patch generated Triton C source");
}

fn write_wrapper(generated_c: &Path, file_name: &str, wrapper_src: String) -> PathBuf {
    let wrapper_path = generated_c
        .parent()
        .expect("generated Triton source should have a parent directory")
        .join(file_name);
    std::fs::write(&wrapper_path, wrapper_src).expect("failed to write Triton wrapper source");
    wrapper_path
}

fn compile_triton_aot_kernels(cuda_include: &Path, out_dir: &Path, sm_targets: &[String]) {
    // Host cc compiles the wrappers below; unlike nvcc it won't find cuda.h itself.
    assert!(
        cuda_include.join("cuda.h").is_file(),
        "cuda.h not found in {}; set CUDA_HOME to a CUDA toolkit root",
        cuda_include.display()
    );
    let python = find_triton_python().unwrap_or_else(|message| panic!("{message}"));
    let triton_target = triton_target(sm_targets);
    let mut generated_sources = Vec::new();
    let root = crate_root();
    let chunkwise_kernel_path = root.join("tools/triton/gated_delta_rule_chunkwise_kernels.py");
    assert!(
        chunkwise_kernel_path.exists(),
        "Qwen3.5 GDR Triton kernel source is missing: {}",
        chunkwise_kernel_path.display()
    );

    {
        let gdr_prepare_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_prepare",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_prepare_qkv_gbeta_qwen35_kernel",
            signature: "*bf16,*bf16,*bf16,*bf16,*fp32,*bf16,*bf16,*bf16,*fp32,*fp32,i32,i32,i32,i32,128,128",
            grid: "seq_len,num_value_heads,1",
            out_name: "triton_gated_delta_rule_chunk_prepare",
            num_warps: 4,
            num_stages: 2,
        };
        let (gdr_prepare_func, gdr_prepare_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_prepare_spec);
        let gdr_prepare_wrapper = write_wrapper(
            &gdr_prepare_c,
            "triton_gated_delta_rule_chunk_prepare_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr qkv, CUdeviceptr b_proj, CUdeviceptr a_proj, CUdeviceptr dt_bias, CUdeviceptr a_log, CUdeviceptr q_out, CUdeviceptr k_out, CUdeviceptr v_out, CUdeviceptr g_out, CUdeviceptr beta_out, int32_t num_key_heads, int32_t num_value_heads, int32_t qkv_dim, int32_t seq_len);\n\nCUresult gated_delta_rule_prefill_chunk_prepare_cuda(const uint16_t* qkv, const uint16_t* b_proj, const uint16_t* a_proj, const uint16_t* dt_bias, const float* a_log, uint16_t* q_out, uint16_t* k_out, uint16_t* v_out, float* g_out, float* beta_out, int32_t num_key_heads, int32_t num_value_heads, int32_t qkv_dim, int32_t seq_len, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)qkv, (CUdeviceptr)b_proj, (CUdeviceptr)a_proj, (CUdeviceptr)dt_bias, (CUdeviceptr)a_log, (CUdeviceptr)q_out, (CUdeviceptr)k_out, (CUdeviceptr)v_out, (CUdeviceptr)g_out, (CUdeviceptr)beta_out, num_key_heads, num_value_heads, qkv_dim, seq_len);\n}}\n",
                func = gdr_prepare_func
            ),
        );
        generated_sources.push(gdr_prepare_c);
        generated_sources.push(gdr_prepare_wrapper);

        let gdr_cumsum_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_cumsum",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_chunk_local_cumsum_qwen35_kernel",
            signature: "*fp32,*fp32,i32,i32,64",
            grid: "(seq_len + 63) / 64,num_value_heads,1",
            out_name: "triton_gated_delta_rule_chunk_cumsum",
            num_warps: 1,
            num_stages: 1,
        };
        let (gdr_cumsum_func, gdr_cumsum_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_cumsum_spec);
        let gdr_cumsum_wrapper = write_wrapper(
            &gdr_cumsum_c,
            "triton_gated_delta_rule_chunk_cumsum_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr g_in, CUdeviceptr g_out, int32_t seq_len, int32_t num_value_heads);\n\nCUresult gated_delta_rule_prefill_chunk_cumsum_cuda(const float* g_in, float* g_out, int32_t seq_len, int32_t num_value_heads, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)g_in, (CUdeviceptr)g_out, seq_len, num_value_heads);\n}}\n",
                func = gdr_cumsum_func
            ),
        );
        generated_sources.push(gdr_cumsum_c);
        generated_sources.push(gdr_cumsum_wrapper);

        let gdr_a_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_a",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_chunk_scaled_dot_kkt_qwen35_kernel",
            signature: "*bf16,*fp32,*fp32,*fp32,i32,i32,64,64,128",
            grid: "(seq_len + 63) / 64,num_value_heads,1",
            out_name: "triton_gated_delta_rule_chunk_a",
            num_warps: 4,
            num_stages: 2,
        };
        let (gdr_a_func, gdr_a_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_a_spec);
        let gdr_a_wrapper = write_wrapper(
            &gdr_a_c,
            "triton_gated_delta_rule_chunk_a_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr k, CUdeviceptr g_cumsum, CUdeviceptr beta, CUdeviceptr a_tril, int32_t seq_len, int32_t num_value_heads);\n\nCUresult gated_delta_rule_prefill_chunk_a_cuda(const uint16_t* k, const float* g_cumsum, const float* beta, float* a_tril, int32_t seq_len, int32_t num_value_heads, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)k, (CUdeviceptr)g_cumsum, (CUdeviceptr)beta, (CUdeviceptr)a_tril, seq_len, num_value_heads);\n}}\n",
                func = gdr_a_func
            ),
        );
        generated_sources.push(gdr_a_c);
        generated_sources.push(gdr_a_wrapper);

        let gdr_solve_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_solve",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_solve_tril_64_qwen35_kernel",
            signature: "*fp32,*bf16,i32,i32",
            grid: "(seq_len + 63) / 64,num_value_heads,1",
            out_name: "triton_gated_delta_rule_chunk_solve",
            num_warps: 4,
            num_stages: 2,
        };
        let (gdr_solve_func, gdr_solve_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_solve_spec);
        let gdr_solve_wrapper = write_wrapper(
            &gdr_solve_c,
            "triton_gated_delta_rule_chunk_solve_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr a_tril, CUdeviceptr a_inv, int32_t seq_len, int32_t num_value_heads);\n\nCUresult gated_delta_rule_prefill_chunk_solve_cuda(const float* a_tril, uint16_t* a_inv, int32_t seq_len, int32_t num_value_heads, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)a_tril, (CUdeviceptr)a_inv, seq_len, num_value_heads);\n}}\n",
                func = gdr_solve_func
            ),
        );
        generated_sources.push(gdr_solve_c);
        generated_sources.push(gdr_solve_wrapper);

        let gdr_recompute_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_recompute",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_recompute_w_u_qwen35_kernel",
            signature: "*bf16,*bf16,*fp32,*bf16,*bf16,*bf16,*fp32,i32,i32,128,128,64,64,64",
            grid: "(seq_len + 63) / 64,num_value_heads,1",
            out_name: "triton_gated_delta_rule_chunk_recompute",
            num_warps: 4,
            num_stages: 2,
        };
        let (gdr_recompute_func, gdr_recompute_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_recompute_spec);
        let gdr_recompute_wrapper = write_wrapper(
            &gdr_recompute_c,
            "triton_gated_delta_rule_chunk_recompute_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr a_inv, CUdeviceptr g_cumsum, int32_t seq_len, int32_t num_value_heads);\n\nCUresult gated_delta_rule_prefill_chunk_recompute_cuda(const uint16_t* k, const uint16_t* v, const float* beta, uint16_t* w, uint16_t* u, const uint16_t* a_inv, const float* g_cumsum, int32_t seq_len, int32_t num_value_heads, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)k, (CUdeviceptr)v, (CUdeviceptr)beta, (CUdeviceptr)w, (CUdeviceptr)u, (CUdeviceptr)a_inv, (CUdeviceptr)g_cumsum, seq_len, num_value_heads);\n}}\n",
                func = gdr_recompute_func
            ),
        );
        generated_sources.push(gdr_recompute_c);
        generated_sources.push(gdr_recompute_wrapper);

        let gdr_chunk_state_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_state",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_chunk_state_qwen35_kernel",
            // `g` (pos 4) stays bare — not a contiguous block-ptr load, so `:16` would be untrue.
            signature: "*bf16:16,*bf16:16,*bf16:16,*fp32,*fp32:16,*fp32:16,*bf16:16,*fp32:16,i32,i32,32,64,128,128,64",
            grid: "4,num_value_heads,1",
            out_name: "triton_gated_delta_rule_chunk_state",
            num_warps: 4,
            num_stages: 2,
        };
        let (gdr_chunk_state_func, gdr_chunk_state_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_chunk_state_spec);
        let gdr_chunk_state_wrapper = write_wrapper(
            &gdr_chunk_state_c,
            "triton_gated_delta_rule_chunk_state_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr k, CUdeviceptr w, CUdeviceptr u, CUdeviceptr g_cumsum, CUdeviceptr initial_state, CUdeviceptr chunk_state, CUdeviceptr v_new, CUdeviceptr final_state, int32_t seq_len, int32_t num_value_heads);\n\nCUresult gated_delta_rule_prefill_chunk_state_cuda(const uint16_t* k, const uint16_t* w, const uint16_t* u, const float* g_cumsum, const float* initial_state, float* chunk_state, uint16_t* v_new, float* final_state, int32_t seq_len, int32_t num_value_heads, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)k, (CUdeviceptr)w, (CUdeviceptr)u, (CUdeviceptr)g_cumsum, (CUdeviceptr)initial_state, (CUdeviceptr)chunk_state, (CUdeviceptr)v_new, (CUdeviceptr)final_state, seq_len, num_value_heads);\n}}\n",
                func = gdr_chunk_state_func
            ),
        );
        generated_sources.push(gdr_chunk_state_c);
        generated_sources.push(gdr_chunk_state_wrapper);

        let gdr_chunk_o_spec = TritonKernelSpec {
            artifact_dir: "gated_delta_rule_chunk_o",
            kernel_path: "tools/triton/gated_delta_rule_chunkwise_kernels.py",
            kernel_name: "gdr_chunk_o_qwen35_kernel",
            signature: "*bf16,*bf16,*bf16,*fp32,*fp32,*bf16,i32,i32,fp32,64,32,64,128,128",
            grid: "4,(seq_len + 63) / 64,num_value_heads",
            out_name: "triton_gated_delta_rule_chunk_o",
            num_warps: 4,
            num_stages: 2,
        };
        let (gdr_chunk_o_func, gdr_chunk_o_c) =
            generate_triton_artifacts(&python, out_dir, &triton_target, &gdr_chunk_o_spec);
        let gdr_chunk_o_wrapper = write_wrapper(
            &gdr_chunk_o_c,
            "triton_gated_delta_rule_chunk_o_wrapper.c",
            format!(
                "#include <cuda.h>\n#include <stdint.h>\n\nCUresult {func}(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v_new, CUdeviceptr chunk_state, CUdeviceptr g_cumsum, CUdeviceptr output, int32_t seq_len, int32_t num_value_heads, float scale);\n\nCUresult gated_delta_rule_prefill_chunk_o_cuda(const uint16_t* q, const uint16_t* k, const uint16_t* v_new, const float* chunk_state, const float* g_cumsum, uint16_t* output, int32_t seq_len, int32_t num_value_heads, float scale, CUstream stream) {{\n    return {func}(stream, (CUdeviceptr)q, (CUdeviceptr)k, (CUdeviceptr)v_new, (CUdeviceptr)chunk_state, (CUdeviceptr)g_cumsum, (CUdeviceptr)output, seq_len, num_value_heads, scale);\n}}\n",
                func = gdr_chunk_o_func
            ),
        );
        generated_sources.push(gdr_chunk_o_c);
        generated_sources.push(gdr_chunk_o_wrapper);
    }

    let mut build = cc::Build::new();
    build
        .cuda(false)
        .include(cuda_include)
        .flag("-std=c11")
        .warnings(false);
    for source in &generated_sources {
        build.file(source);
    }
    time_phase("cc triton_kernels_aot", || {
        build.compile("triton_kernels_aot");
    });

    println!("cargo:rustc-link-lib=cuda");
    println!(
        "cargo:warning=Using Triton AOT for Qwen3.5 GDR chunkwise prefill; basic ops (add, silu_mul, embedding) use native CUDA"
    );
    println!(
        "cargo:rerun-if-changed={}",
        root.join("tools/triton/gated_delta_rule_chunkwise_kernels.py")
            .display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        root.join("tools/triton/gen_triton_aot.py").display()
    );
    println!("cargo:rerun-if-env-changed=PEGAINFER_TRITON_PYTHON");
}

fn main() {
    ensure_git_submodules_initialized(&workspace_root());

    let toolkit = pegainfer_build::CudaToolkit::discover();
    let nvcc = toolkit.nvcc.to_string_lossy().into_owned();
    let cuda_include = toolkit
        .header_dir("cuda.h")
        .unwrap_or_else(|| toolkit.root.join("include"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let sm_targets = detect_sm_targets();
    let nvcc_sm_targets = normalize_nvcc_sms(&sm_targets, &nvcc);
    let arch_args = nvcc_arch_args(&nvcc_sm_targets);
    let deepseek_v2_lite_enabled = cfg!(feature = "deepseek-v2-lite");
    let moe_enabled = cfg!(feature = "moe");
    let glm52_enabled = cfg!(feature = "glm52");
    let higgs_audio_enabled = cfg!(feature = "higgs-audio");
    let kimi_k2_enabled = cfg!(feature = "kimi-k2");
    let qwen35_enabled = cfg!(feature = "qwen35");
    if glm52_enabled {
        generate_glm52_trtllm_fmha_cubins(&crate_root(), &out_dir);
        build_glm52_cutedsl_fp8_dsl(&crate_root(), &out_dir, &cuda_include);
    }
    println!(
        "cargo:warning=Detected CUDA SM targets: {}",
        sm_targets
            .iter()
            .map(|sm| format!("sm_{sm}"))
            .collect::<Vec<_>>()
            .join(",")
    );
    println!(
        "cargo:warning=Compiling CUDA kernels for nvcc targets: {}",
        nvcc_sm_targets
            .iter()
            .map(|sm| format!("sm_{sm}"))
            .collect::<Vec<_>>()
            .join(",")
    );

    let replaced_cuda_files =
        BTreeSet::from(["activation.cu", "embedding.cu", "fused_attention.cu"]);

    let root = crate_root();
    if moe_enabled {
        require_moe_submodules(&root);
    }
    if glm52_enabled {
        require_glm52_submodules(&root);
    }
    let csrc_dir = root.join("csrc");
    let mut csrc_files = Vec::new();
    collect_files_recursively(&csrc_dir, &mut csrc_files);
    let mut cu_files: Vec<_> = csrc_files
        .iter()
        .filter_map(|path| {
            let file_name = path.file_name()?.to_str()?;
            if !deepseek_v2_lite_enabled && is_deepseek_v2_lite_source(&csrc_dir, path) {
                return None;
            }
            if !moe_enabled && is_deepep_source(&csrc_dir, path) {
                return None;
            }
            // The GLM5.2 shim instantiations (EP4..EP64) ride the deepep
            // flags but only exist for the glm52 feature.
            if !glm52_enabled && file_name.starts_with("deepep_shim_glm52") {
                return None;
            }
            if !glm52_enabled && is_glm52_source(&csrc_dir, path) {
                return None;
            }
            if !higgs_audio_enabled && is_higgs_audio_source(&csrc_dir, path) {
                return None;
            }
            if !kimi_k2_enabled && is_kimi_k2_source(&csrc_dir, path) {
                return None;
            }
            if path.extension().and_then(|e| e.to_str()) == Some("cu")
                && !replaced_cuda_files.contains(file_name)
            {
                Some(path.clone())
            } else {
                None
            }
        })
        .collect();
    cu_files.sort();
    for path in &csrc_files {
        let Some(extension) = path.extension().and_then(|extension| extension.to_str()) else {
            continue;
        };
        if matches!(extension, "cu" | "cuh") {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    println!(
        "cargo:warning=Legacy CUDA translation units retired from the runtime build: {}",
        replaced_cuda_files
            .iter()
            .copied()
            .collect::<Vec<_>>()
            .join(", ")
    );

    let nvcc_jobs = nvcc_job_count();
    println!("cargo:warning=Compiling CUDA translation units with {nvcc_jobs} nvcc job(s)");
    let flashinfer = flashinfer_includes();
    println!(
        "cargo:warning=Using FlashInfer include dir: {}",
        flashinfer.include.display()
    );

    let deepep_nccl = moe_enabled.then(deepep_nccl_root);

    let mut nvcc_tasks = Vec::new();
    for cu_file in &cu_files {
        let stem = cu_file.file_stem().unwrap().to_str().unwrap();
        let obj_file = out_dir.join(cuda_object_name(&csrc_dir, cu_file));

        let mut nvcc_args = vec![
            "-c".to_string(),
            cu_file.to_string_lossy().to_string(),
            "-o".to_string(),
            obj_file.to_string_lossy().to_string(),
            "-O3".to_string(),
            "-isystem".to_string(),
            cuda_include.to_string_lossy().to_string(),
            "-I".to_string(),
            csrc_dir.to_string_lossy().to_string(),
        ];
        if stem == "glm52_fp8_gemm" {
            if let Some(args) = glm52_fp8_gemm_arch_args(&nvcc_sm_targets, &nvcc) {
                nvcc_args.extend(args);
                nvcc_args.push("-DGLM52_FP8_GEMM_SM100A".to_string());
            } else {
                nvcc_args.extend(arch_args.clone());
            }
        } else if stem == "glm52_flashmla_sparse" {
            nvcc_args.extend(glm52_flashmla_sparse_arch_args(&nvcc_sm_targets, &nvcc));
        } else if stem == "glm52_deepgemm_mqa" {
            if let Some((mqa_args, mqa_define)) =
                glm52_deepgemm_mqa_arch_args(&nvcc_sm_targets, &nvcc)
            {
                nvcc_args.extend(mqa_args);
                nvcc_args.push(mqa_define);
            } else {
                println!(
                    "cargo:warning=No sm_100f target; GLM5.2 DeepGEMM {stem} kernels compile as NOT_SUPPORTED stubs"
                );
                nvcc_args.extend(arch_args.clone());
            }
        } else if stem == "glm52_deepgemm_grouped_sm100" {
            if let Some(sm100f_args) = glm52_sm100f_only_arch_args(&nvcc_sm_targets, &nvcc) {
                nvcc_args.extend(sm100f_args);
                nvcc_args.push("-DGLM52_DEEPGEMM_GROUPED_SM100F".to_string());
            } else {
                println!(
                    "cargo:warning=No sm_100f target; GLM5.2 DeepGEMM {stem} kernels compile as NOT_SUPPORTED stubs"
                );
                nvcc_args.extend(arch_args.clone());
            }
        } else {
            nvcc_args.extend(arch_args.clone());
        }
        nvcc_args.extend(["--compiler-options".to_string(), "-fPIC".to_string()]);

        // Files that include FlashInfer headers (C++17, header-only)
        if stem == "paged_attention"
            || stem == "paged_attention_hd512"
            || stem == "flashinfer_norm"
            || stem == "flashinfer_sampling"
            || stem == "flashinfer_top1"
            || stem == "glm52_topk"
        {
            for dir in &flashinfer.cccl {
                nvcc_args.extend(["-I".to_string(), dir.to_string_lossy().to_string()]);
            }
            nvcc_args.extend([
                "--std=c++17".to_string(),
                "-I".to_string(),
                flashinfer.include.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.csrc.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass_util.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.spdlog.to_string_lossy().to_string(),
                "-I".to_string(),
                csrc_dir
                    .join("kimi_k2/vllm_marlin")
                    .to_string_lossy()
                    .to_string(),
            ]);
        }

        // DeepEP elastic shim: mirrors the upstream JIT compile flags
        // (DeepEP csrc/jit/compiler.hpp) minus the cubin plumbing.
        if is_deepep_source(&csrc_dir, cu_file) {
            let nccl_root = deepep_nccl
                .as_ref()
                .expect("deepep sources are collected only with the moe feature");
            nvcc_args.extend(
                [
                    "--std=c++20",
                    "--expt-relaxed-constexpr",
                    "--expt-extended-lambda",
                    "--diag-suppress=39,68,161,174,177,186,940,3012",
                    "-Xptxas",
                    "--register-usage-level=10",
                    "-DEP_NUM_TOPK_IDX_BITS=32",
                ]
                .map(str::to_string),
            );
            nvcc_args.extend([
                "-I".to_string(),
                root.join("third_party/DeepEP/deep_ep/include")
                    .to_string_lossy()
                    .to_string(),
                "-I".to_string(),
                nccl_root.join("include").to_string_lossy().to_string(),
            ]);
        }

        if stem.starts_with("kimi_") {
            for dir in &flashinfer.cccl {
                nvcc_args.extend(["-I".to_string(), dir.to_string_lossy().to_string()]);
            }
            nvcc_args.extend([
                "--std=c++17".to_string(),
                "--expt-relaxed-constexpr".to_string(),
                "-I".to_string(),
                flashinfer.include.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.csrc.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass_util.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.spdlog.to_string_lossy().to_string(),
                "-I".to_string(),
                csrc_dir
                    .join("kimi_k2/vllm_marlin")
                    .to_string_lossy()
                    .to_string(),
            ]);
        }

        if stem == "glm52_flashmla_sparse" {
            let flashmla = root.join("third_party/FlashMLA/csrc");
            nvcc_args.extend([
                "--std=c++20".to_string(),
                "--expt-relaxed-constexpr".to_string(),
                "--expt-extended-lambda".to_string(),
                "-I".to_string(),
                flashmla.to_string_lossy().to_string(),
                "-I".to_string(),
                flashmla
                    .join("cutlass/include")
                    .to_string_lossy()
                    .to_string(),
                "-I".to_string(),
                flashmla
                    .join("cutlass/tools/util/include")
                    .to_string_lossy()
                    .to_string(),
                "-I".to_string(),
                flashmla
                    .join("kerutils/include")
                    .to_string_lossy()
                    .to_string(),
                "-I".to_string(),
                flashinfer.cutlass.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass_util.to_string_lossy().to_string(),
            ]);
        } else if stem == "glm52_fp8_gemm" {
            for dir in &flashinfer.cccl {
                nvcc_args.extend(["-I".to_string(), dir.to_string_lossy().to_string()]);
            }
            nvcc_args.extend([
                "--std=c++17".to_string(),
                "--expt-relaxed-constexpr".to_string(),
                "--expt-extended-lambda".to_string(),
                "-I".to_string(),
                flashinfer.include.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass_util.to_string_lossy().to_string(),
            ]);
        } else if stem == "glm52_flashinfer_sparse" {
            for dir in &flashinfer.cccl {
                nvcc_args.extend(["-I".to_string(), dir.to_string_lossy().to_string()]);
            }
            nvcc_args.extend([
                "--std=c++17".to_string(),
                "--expt-relaxed-constexpr".to_string(),
                "--expt-extended-lambda".to_string(),
                "-DTLLM_GEN_FMHA_CUBIN_PATH=\"embedded\"".to_string(),
                "-DTLLM_GEN_FMHA_METAINFO_HASH=\"pegainfer-glm52-sm100f\"".to_string(),
                "-I".to_string(),
                out_dir.to_string_lossy().to_string(),
                "-I".to_string(),
                csrc_dir
                    .join("glm52/trtllm_gen")
                    .to_string_lossy()
                    .to_string(),
                "-I".to_string(),
                flashinfer.include.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.csrc.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.cutlass_util.to_string_lossy().to_string(),
                "-I".to_string(),
                flashinfer.spdlog.to_string_lossy().to_string(),
            ]);
        } else if stem == "glm52_deepgemm_mqa" || stem == "glm52_deepgemm_grouped_sm100" {
            // DeepGEMM MQA + masked grouped GEMM kernels,
            // AOT-instantiated from the vendored device headers (torch-free
            // via DG_NO_TORCH, no runtime JIT). Needs DeepGEMM csrc headers +
            // CUTLASS + fmt, C++20.
            let deepgemm_root = root.join("third_party/DeepGEMM");
            let deepgemm_csrc = deepgemm_root.join("csrc");
            let deepgemm_include = deepgemm_root.join("deep_gemm/include");
            let cutlass_include = deepgemm_root.join("third-party/cutlass/include");
            let cutlass_util = deepgemm_root.join("third-party/cutlass/tools/util/include");
            let fmt_include = deepgemm_root.join("third-party/fmt/include");
            nvcc_args.extend([
                "--std=c++20".to_string(),
                "--expt-relaxed-constexpr".to_string(),
                "--expt-extended-lambda".to_string(),
                "-DDG_NO_TORCH".to_string(),
                "-I".to_string(),
                deepgemm_csrc.to_string_lossy().to_string(),
                "-I".to_string(),
                deepgemm_include.to_string_lossy().to_string(),
                "-I".to_string(),
                cutlass_include.to_string_lossy().to_string(),
                "-I".to_string(),
                cutlass_util.to_string_lossy().to_string(),
                "-I".to_string(),
                fmt_include.to_string_lossy().to_string(),
            ]);
        } else if stem.starts_with("glm52_") {
            nvcc_args.extend(["--std=c++17".to_string()]);
        } else if stem.starts_with("higgs_") {
            nvcc_args.extend(["--std=c++17".to_string()]);
        }

        nvcc_tasks.push(NvccTask {
            cu_file: cu_file.clone(),
            obj_file,
            args: nvcc_args,
        });
    }

    if !moe_enabled {
        println!(
            "cargo:warning=MoE third-party substrate disabled; enable the pegainfer-kernels `moe` feature to build DeepEP-backed kernels"
        );
    }
    if !glm52_enabled {
        println!(
            "cargo:warning=GLM5.2 DeepGEMM/FlashMLA interfaces disabled; enable the pegainfer-kernels `glm52` feature to build them"
        );
    }
    if !higgs_audio_enabled {
        println!(
            "cargo:warning=Higgs-Audio CUDA kernels disabled; enable the pegainfer-kernels `higgs-audio` feature to build them"
        );
    }
    if !kimi_k2_enabled {
        println!(
            "cargo:warning=Kimi-K2 CUDA kernels disabled; enable the pegainfer-kernels `kimi-k2` feature to build them"
        );
    }

    nvcc_tasks.sort_by_key(|task| nvcc_task_priority(&task.cu_file));

    let task_queue = Mutex::new(VecDeque::from(nvcc_tasks));
    let nvcc_workers = nvcc_jobs.min(task_queue.lock().expect("task queue poisoned").len());
    let mut obj_files = Vec::new();
    thread::scope(|scope| {
        let handles: Vec<_> = (0..nvcc_workers)
            .map(|_| {
                let task_queue = &task_queue;
                let nvcc = nvcc.clone();
                scope.spawn(move || {
                    let mut completed = Vec::new();
                    loop {
                        let task = task_queue.lock().expect("task queue poisoned").pop_front();
                        let Some(task) = task else {
                            break;
                        };

                        let status = time_phase(format!("nvcc {}", task.cu_file.display()), || {
                            Command::new(&nvcc)
                                .args(&task.args)
                                .status()
                                .unwrap_or_else(|_| {
                                    panic!("Failed to run nvcc for {}", task.cu_file.display())
                                })
                        });
                        completed.push((task.cu_file, task.obj_file, status));
                    }
                    completed
                })
            })
            .collect();

        for handle in handles {
            for (cu_file, obj_file, status) in handle.join().expect("nvcc worker panicked") {
                assert!(
                    status.success(),
                    "nvcc compilation failed for {}",
                    cu_file.display()
                );
                obj_files.push(obj_file);
            }
        }
    });
    obj_files.sort();

    // The optional kernel-lab .so (linked below) uses the same objects; the
    // ar invocation consumes the vector.
    let kernel_lab_objs = obj_files.clone();

    let cuda_lib = out_dir.join("libkernels_cuda.a");
    let _ = fs::remove_file(&cuda_lib);
    let mut ar_args = vec!["rcs".to_string(), cuda_lib.to_string_lossy().to_string()];
    ar_args.extend(
        obj_files
            .into_iter()
            .map(|path| path.to_string_lossy().to_string()),
    );

    let status = time_phase("ar libkernels_cuda.a", || {
        Command::new("ar")
            .args(&ar_args)
            .status()
            .expect("Failed to run ar")
    });

    assert!(status.success(), "ar failed");

    // Optional kernel-lab shared object for the Python bench harness
    // (pegainfer-glm52/benches/kernel_lab): the exact production objects —
    // same sources, same nvcc flags — linked as a dlopen-able .so. Skipped
    // entirely unless PEGAINFER_KERNEL_LAB is set, so default builds run zero
    // extra commands and zero extra link lines.
    if std::env::var_os("PEGAINFER_KERNEL_LAB").is_some() {
        link_kernel_lab_shared(&nvcc, &toolkit, &out_dir, &kernel_lab_objs);
    }

    if qwen35_enabled {
        compile_triton_aot_kernels(&cuda_include, &out_dir, &sm_targets);
    } else {
        println!(
            "cargo:warning=Qwen3.5 Triton AOT kernels disabled; enable the pegainfer-kernels `qwen35` feature to build them (needs Python + Triton at build time)"
        );
    }

    println!("cargo:rustc-link-search=native={}", out_dir.display());
    if cfg!(target_os = "windows") {
        println!(
            "cargo:rustc-link-search=native={}/lib/x64",
            toolkit.root.display()
        );
    } else {
        toolkit.link_search();
    }
    println!("cargo:rustc-link-lib=static=kernels_cuda");
    println!("cargo:rustc-link-lib=cudart");
    println!("cargo:rustc-link-lib=cublas");
    println!("cargo:rustc-link-lib=cublasLt");
    // DeepGEMM JIT runtime calls cuLibraryLoadData etc. (CUDA 12.6+ driver API);
    // libcuda.so lives in the system lib dir, not the toolkit dir.
    println!("cargo:rustc-link-lib=cuda");
    // DeepGEMM compiler.hpp references nvrtc symbols (NVRTCCompiler class).
    println!("cargo:rustc-link-lib=nvrtc");
    if let Some(nccl_root) = &deepep_nccl {
        link_deepep_nccl(nccl_root, &out_dir);
    }
    if !cfg!(target_os = "windows") {
        println!("cargo:rustc-link-lib=stdc++");
    }

    println!("cargo:rerun-if-changed={}", root.join("csrc").display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=PEGAINFER_CUDA_SM");
    println!("cargo:rerun-if-env-changed=CUDA_SM");
    println!("cargo:rerun-if-env-changed=PEGAINFER_FLASHINFER_INCLUDE");
    println!("cargo:rerun-if-env-changed=PEGAINFER_BUILD_TIMING");
    println!("cargo:rerun-if-env-changed=PEGAINFER_NVCC_JOBS");
    println!("cargo:rerun-if-env-changed=PEGAINFER_NCCL_ROOT");
    let mut tracked_dirs = vec![
        flashinfer.include.clone(),
        flashinfer.csrc.clone(),
        flashinfer.cutlass.clone(),
        flashinfer.cutlass_util.clone(),
        flashinfer.spdlog.clone(),
    ];
    tracked_dirs.extend(flashinfer.cccl.iter().cloned());
    tracked_dirs.push(root.join("third_party/DeepEP/deep_ep/include"));
    tracked_dirs.push(root.join("third_party/DeepGEMM"));
    tracked_dirs.push(root.join("third_party/FlashMLA"));
    for dir in tracked_dirs {
        if dir.exists() {
            println!("cargo:rerun-if-changed={}", dir.display());
        }
    }
}
